-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 97b88d9610bcc03982ddac33caba98bb2b751f5f
    hooks:
    -   id: trailing-whitespace
    -   id: autopep8-wrapper
        args:
        - -i
        - --ignore=E501
    -   id: end-of-file-fixer
    -   id: pretty-format-json
    -   id: check-merge-conflict
    -   id: flake8
        args:
        - --ignore=E501
